// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB_DuQh2xZ2Cl3oBOo0hL-kB-drVycsTI',
    appId: '1:111710858133:web:017dd33edb41dcf87ce49c',
    messagingSenderId: '111710858133',
    projectId: 'automatedlaundromatcoe420',
    authDomain: 'automatedlaundromatcoe420.firebaseapp.com',
    databaseURL: 'https://automatedlaundromatcoe420-default-rtdb.firebaseio.com',
    storageBucket: 'automatedlaundromatcoe420.appspot.com',
    measurementId: 'G-M0KPKYFFCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG3uzc1Drsuc16auSNN9U1VhPDU4zScNQ',
    appId: '1:111710858133:android:b314f008386ead097ce49c',
    messagingSenderId: '111710858133',
    projectId: 'automatedlaundromatcoe420',
    databaseURL: 'https://automatedlaundromatcoe420-default-rtdb.firebaseio.com',
    storageBucket: 'automatedlaundromatcoe420.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJmV5H0sDGpPzVi3UxLhuhQbTf3_YxeH4',
    appId: '1:111710858133:ios:17e5515404ad03b27ce49c',
    messagingSenderId: '111710858133',
    projectId: 'automatedlaundromatcoe420',
    databaseURL: 'https://automatedlaundromatcoe420-default-rtdb.firebaseio.com',
    storageBucket: 'automatedlaundromatcoe420.appspot.com',
    iosBundleId: 'com.example.automatedLaudromat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJmV5H0sDGpPzVi3UxLhuhQbTf3_YxeH4',
    appId: '1:111710858133:ios:17e5515404ad03b27ce49c',
    messagingSenderId: '111710858133',
    projectId: 'automatedlaundromatcoe420',
    databaseURL: 'https://automatedlaundromatcoe420-default-rtdb.firebaseio.com',
    storageBucket: 'automatedlaundromatcoe420.appspot.com',
    iosBundleId: 'com.example.automatedLaudromat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB_DuQh2xZ2Cl3oBOo0hL-kB-drVycsTI',
    appId: '1:111710858133:web:7e254fccf0dece287ce49c',
    messagingSenderId: '111710858133',
    projectId: 'automatedlaundromatcoe420',
    authDomain: 'automatedlaundromatcoe420.firebaseapp.com',
    databaseURL: 'https://automatedlaundromatcoe420-default-rtdb.firebaseio.com',
    storageBucket: 'automatedlaundromatcoe420.appspot.com',
    measurementId: 'G-8HB800G1YM',
  );

}